---

kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: default
  name: traefik
  labels:
    app: traefik

spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      serviceAccountName: traefik-ingress-controller
      containers:
        - name: traefik
          image: traefik:v2.3
          args:
            - --api.insecure
            #- --providers.file.directory=/path/to/dynamic/conf
            - --providers.kubernetescrd
            - --providers.kubernetesingress
            - --accesslog
            #- --entrypoints.file.directory=/etc/traefik/config/entrypoints.yml
            - --entrypoints.web.Address=:8000
            - --entrypoints.websecure.Address=:4443
          resources:
            limits:
              cpu: "0.5"
              memory: 150m
            requests:
              cpu: "0.25"
              memory: 100m
          ports:
            - name: web
              containerPort: 8000
            - name: admin
              containerPort: 8080
          volumeMounts:
            - name: config-endpoints
              mountPath: /etc/traefik/config
      volumes:
        - name: config-endpoints
          configMap:
            name: traefik-config-entrypoints
            items:
              - key: entrypoints.yml
                path: endpoints.yml
